name: khalti_checkout_core
description: An official wrapper around Khalti Payment Gateway's REST API.
version: 1.0.0-dev.5
homepage: https://khalti.com/payment-gateway/
documentation: https://docs.khalti.com/
issue_tracker: https://github.com/khalti/checkout-sdk-flutter/issues
repository: https://github.com/khalti/checkout-sdk-flutter/tree/main/packages/khalti_checkout_core

environment:
  sdk: ">=3.2.0 <4.0.0"

platforms:
  android:
  ios:

dependencies:
  device_info_plus: ^10.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  meta: ^1.11.0
  package_info_plus: ^8.0.1

dev_dependencies:
  flutter_lints: ^3.0.1
  mocktail: ^1.0.3
  package_info_plus_platform_interface: ^3.0.0
  plugin_platform_interface: ^2.1.8
  test: ^1.25.2
